"""Synthetic, project-owned index fixture used only by container readiness CI."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from PIL import Image

from fluke_model.embedders import (
    DINO_V2_MODEL_ID,
    DINO_V2_REVISION,
    LoadedEmbedder,
    load_embedder,
)
from fluke_model.identify_runtime import ReferencePhoto, build_reference_index
from fluke_model.index_store import AtomicIndexStore
from fluke_model.rights import DataRights, ModelRights, RightsAttestation


def build_ci_reference_index(
    out_dir: Path,
    *,
    artifact_dir: Path | None = None,
    embedder: LoadedEmbedder | None = None,
) -> None:
    local_embedder = embedder or _load_local_embedder(artifact_dir)
    references = (
        ReferencePhoto(
            "ci-black",
            "CI-BLACK",
            "Synthetic black fixture",
            "https://ci.invalid/black.jpg",
            "fluke-ci-generated",
        ),
        ReferencePhoto(
            "ci-white",
            "CI-WHITE",
            "Synthetic white fixture",
            "https://ci.invalid/white.jpg",
            "fluke-ci-generated",
        ),
    )
    query = Image.new("RGB", (224, 224), color=(0, 0, 0))
    try:
        out_dir.mkdir(parents=True, exist_ok=True)
        query.save(out_dir / "ci-query.jpg", format="JPEG")
    finally:
        query.close()
    build_reference_index(
        list(references),
        store=AtomicIndexStore(out_dir),
        rights=_ci_rights(),
        embedder=local_embedder,
        image_loader=_fixture_image,
    )


def _load_local_embedder(artifact_dir: Path | None) -> LoadedEmbedder:
    if artifact_dir is None:
        raise ValueError("CI model artifact directory is required")
    return load_embedder("dinov2-small", artifact_dir=artifact_dir)


def _fixture_image(reference: ReferencePhoto) -> Image.Image:
    color = (0, 0, 0) if reference.catalog_id == "CI-BLACK" else (255, 255, 255)
    return Image.new("RGB", (224, 224), color=color)


def _ci_rights() -> RightsAttestation:
    return RightsAttestation(
        schema_version=1,
        approved_by="Fluke CI synthetic fixture",
        approved_at=datetime(2026, 7, 17, tzinfo=timezone.utc),
        commercial_use_allowed=True,
        model=ModelRights(
            model_id=DINO_V2_MODEL_ID,
            revision=DINO_V2_REVISION,
            license_spdx="Apache-2.0",
            evidence_url="https://github.com/facebookresearch/dinov2/blob/main/LICENSE",
            commercial_use_allowed=True,
        ),
        data_sources=(
            DataRights(
                source_id="fluke-ci-generated",
                license_or_permission="generated by Fluke CI; no third-party input",
                evidence_url="https://ci.invalid/fluke-generated-fixture",
                commercial_use_allowed=True,
            ),
        ),
    )
